### ISSUE TITLE
可以直接用xposed api写xposed框架吗？

### ISSUE THREAD

**Issue by ebitgeek** [ganyao114/SandHook#66]
只依赖sandhook 的xposed api 可以直接用来写xposed框架 导入edxposed运行吗？
![image](https://user-images.githubusercontent.com/48763080/94333599-f7618080-0009-11eb-926b-47b9919931b8.png)
![image](https://user-images.githubusercontent.com/48763080/94334038-19f39980-000a-11eb-9713-96888f7c6dbb.png)
![image](https://user-images.githubusercontent.com/48763080/94334192-2546c500-000a-11eb-80a8-b41483fb9646.png)
![image](https://user-images.githubusercontent.com/48763080/94334297-2d9f0000-000a-11eb-88bf-f8969e0b3505.png)
![image](https://user-images.githubusercontent.com/48763080/94334989-ba49be00-000a-11eb-8f12-bbf4376aa6b3.png)
![image](https://user-images.githubusercontent.com/48763080/94335026-0694fe00-000b-11eb-948d-a7b1fda9e103.png)
![image](https://user-images.githubusercontent.com/48763080/94335036-17457400-000b-11eb-8374-6e1ad032b196.png)
![image](https://user-images.githubusercontent.com/48763080/94335040-262c2680-000b-11eb-9d58-8616e5b8ab31.png)

我写了个hook本进程的小案例，可是在手机安装 ed xposed以后并不能成功HOOK

**Comment by belian001** [comment]
请问用sandx

> 只依赖sandhook 的xposed api 可以直接用来写xposed框架 导入edxposed运行吗？ ![image](https://user-images.githubusercontent.com/48763080/94333599-f7618080-0009-11eb-926b-47b9919931b8.png) ![image](https://user-images.githubusercontent.com/48763080/94334038-19f39980-000a-11eb-9713-96888f7c6dbb.png) ![image](https://user-images.githubusercontent.com/48763080/94334192-2546c500-000a-11eb-80a8-b41483fb9646.png) ![image](https://user-images.githubusercontent.com/48763080/94334297-2d9f0000-000a-11eb-88bf-f8969e0b3505.png) ![image](https://user-images.githubusercontent.com/48763080/94334989-ba49be00-000a-11eb-8f12-bbf4376aa6b3.png) ![image](https://user-images.githubusercontent.com/48763080/94335026-0694fe00-000b-11eb-948d-a7b1fda9e103.png) ![image](https://user-images.githubusercontent.com/48763080/94335036-17457400-000b-11eb-8374-6e1ad032b196.png) ![image](https://user-images.githubusercontent.com/48763080/94335040-262c2680-000b-11eb-9d58-8616e5b8ab31.png)
> 
> 我写了个hook本进程的小案例，可是在手机安装 ed xposed以后并不能成功HOOK

你解决了吗？我也试过用sandhook 的xposed api编写xposed 模块，发现不能被加载，用的lsposed
2022-05-10 23:02:16.281 11674-11674/? I/LSPosed-Bridge: Loading module com.sandhook.xposed from /data/user/0/com.ecomi.xposed/cache/lspatch/com.sandhook.xposed/4238802665
2022-05-10 23:02:16.404 11674-11674/? E/LSPosed-Bridge:   Cannot load module: com.sandhook.xposed
2022-05-10 23:02:16.404 11674-11674/? E/LSPosed-Bridge:   The Xposed API classes are compiled into the module's APK.
2022-05-10 23:02:16.404 11674-11674/? E/LSPosed-Bridge:   This may cause strange issues and must be fixed by the module developer.
2022-05-10 23:02:16.404 11674-11674/? E/LSPosed-Bridge:   For details, see: https://api.xposed.info/using.html
